### ISSUE TITLE
.NET Framework 4.5 support

### ISSUE THREAD

**Issue by jisotalo** [leocb/MaterialSkin#104]
Hi!

Just found out your version of this project. Awesome.

I noticed that the project has target framework version of v4.6.1. I have a case where the target platform has 4.5.1 installed and it's not possible to install 4.6.1 easily. I cloned the project and changed framework to 4.5 and everything works fine.

Just curious, would it be possible to change it to 4.5 instead? I know I can compile it myself, just thinking would that make any sense? Or is it a general convention to use the latest available?

Keep up the good work!

**Comment by leocb** [comment]
I honestly don't know what limitations there would be if I downgraded the minimum required framework version, nor do I know the conventions for libs and projects. It's on 4.6.1 because that's what my project used at the time, no other particular reason. 

Theoretically I could even downgrade it to 4.0 without any problems. more testing is required.

Currently I'm not actively working on this lib. maybe in the future I'll change it :)
