### ISSUE TITLE
Drawer improvements

### ISSUE THREAD

**Issue by emgie123** [leocb/MaterialSkin#124]
Hi, great work!

While playing with the lib I am missing quite important functionality as event on drawer icon click which I could bind to.
Another thing is that it would be nice if there was a possibility to open the drawer on hover (when show icons on hidden mode) #

**Comment by leocb** [comment]
Hi, glad you're enjoying it :)
The drawer is basically a glorified tab selector, you can subscribe to the `SelectedIndexChanged` event of the MaterialTabControl and it should work as you want.
Opening the drawer on hover is not something I plan on implementing, you could do it yourself, just modify the material drawer and call the Show() method on hover, modify the Material Form and call drawerControl.Hide() method on the hover of the overlay (currently it uses a click on the overlay),
If you want to toggle between just icon and full modes, it'll be a little more complicated since it doesn't have the animation for switching between these modes.
Good luck

**Comment by emgie123** [comment]
Hi,

After creating this issue found out the events you are writing about and used that to accomplish what I need - it is good enough. Thanks for your quick response and advice I will try to do so with the drawer! :)

**Comment by orapps44** [comment]
Hi, 

@leocb , congratulations for your work !

@emgie123 I'm also interested by MouseHover functionality. Do you mind to share your code updates ?

Thx

**Comment by emgie123** [comment]
@orapps44 Hi I unfortunately it sometimes had some problems i.e. when the form was just stared and the mouse was on the drawer in that time, the drawer falls into infinite loop "on enter"/"on leave". At the moment I haven`t work it out as had to push the project further so left with the standard(on click) functionality

**Comment by leocb** [comment]
Try the recent pr #128

**Comment by orapps44** [comment]
Drawer open on hover feature has been added with PR #128 & PR #172.

**Comment by orapps44** [comment]
Event on drawer icon click doesn't exist but you can use SelectedIndexChanged event from Drawer tab control instead.
