### ISSUE TITLE
I can't input the Hangul in MaterialTextBox Control

### ISSUE THREAD

**Issue by acinside** [leocb/MaterialSkin#186]
hi~
MaterialTextBox
![테스](https://user-images.githubusercontent.com/80085441/121619924-5685f900-caa4-11eb-8ee0-e57b3e37b7de.png)

Normal TextBox
![트테스](https://user-images.githubusercontent.com/80085441/121619996-81704d00-caa4-11eb-8ee7-809dbc7dd549.png)

There is a problem Hangul input

and when you longtext in a text box the cursor is misplaced (It doesn't happen in the example app, it happens in a new project)
![error](https://user-images.githubusercontent.com/80085441/121620317-183d0980-caa5-11eb-8fd8-6a94f84609a6.png)

**Comment by TomsDev67** [comment]
I also have the behavior of misplaced cursor in textbox with password property = true.

**Comment by orapps44** [comment]
Hi,

Thanks for reporting issue.
Are you using Dense property = true ?

**Comment by acinside** [comment]
Are you using UseTallSize property = false ?
-> No

Are you able to reproduce this issue with MaterialTextBox in MaterialSkinExample ?
-> Cursor issue does not occur, but i can't input the Hangul

**Comment by TomsDev67** [comment]
Just to complete, on my side UseTallSize = True

**Comment by orapps44** [comment]
> 
> 
> Are you using UseTallSize property = false ?
> -> No
> 
> Are you able to reproduce this issue with MaterialTextBox in MaterialSkinExample ?
> -> Cursor issue does not occur, but i can't input the Hangul

Was Hangul input working with previous release ? 
If yes, which release were you using ?

**Comment by acinside** [comment]
Was Hangul input working with previous release ?
->No

If yes, which release were you using ?
->I am using 2.2.0 release

**Comment by orapps44** [comment]
Hangul isn't supported yet (see #147).
Feel free to contribute by doing a PR.

However a cursor misplaced bug remains.

**Comment by orapps44** [comment]
Hi @acinside ,

Could try latest PR #195 with Hangul ?

**Comment by DoubleDebug** [comment]
I had the same issue, even though I was writing pure English.

I think the error has to do with setting the text of the textbox through code (e.g. materialTextBox1.Text = "example").
Whenever I did that, the cursor got messed up in the UI. However, I never had issues when the textbox was empty and I manually typed the text in the UI, if that makes sense.

**Comment by orapps44** [comment]
@DoubleDebug : Are you able to reproduce this behaviour with example project ?

**Comment by DoubleDebug** [comment]
Unfortunately, even though it is still happening in my project, I wasn't able to reproduce it in a sample project.
However I did with a password textbox and the bug persists, as @acinside pointed out.

The bug occurs whenever you start typing in the textbox, the text doesn't have to be set through code. The textbox is still functional, but the cursor is misplaced. Here's a gif of the visual bug.

![visual_bug](https://user-images.githubusercontent.com/62041862/125706189-9a678678-995d-4eed-9797-f67d947401eb.gif)

And here is the example project:

[Example.zip](https://github.com/leocb/MaterialSkin/files/6819434/Example.zip)

**Comment by acinside** [comment]
> 안녕하세요 @acinside 입니다 .
> 
> 최신 PR #195 를 한글로 사용해 볼 수 있습니까?

**Comment by acinside** [comment]
> Hi @acinside ,
> 
> Could try latest PR #195 with Hangul ?


same issue

**Comment by orapps44** [comment]
Roboto supports Latin, Greek (partial) and Cyrillic scripts.
On Android, the Noto font is used for languages not supported by Roboto, including Chinese (simplified and traditional), Japanese, Korean, Thai and Hindi.

So Hangul input doesn't work because only Roboto font is currentely supported. 
To use Hangul and all other languages not supported by Roboto, Noto font support is required.

Feel free to contribute.

**Comment by oAllen1** [comment]
I meet the misplaced cursor bug too. 
I only use English font and find out the misplaced error occurs in my own project but there is no problem in the example project. 
The reason is the target framework version of the example project  is .NET Framework 4.6.1 and my own project is .NET Framework 4.7.2. 
Can you adapt this example project to new version 4.7.2？

**Comment by orapps44** [comment]
@DoubleDebug  , @oAllen1 , @TomsDev67 

I've made a PR to fix Textbox beam cursor misplaced, it works fine on my side.
Could you try it ?
https://github.com/leocb/MaterialSkin/tree/orapps44-patch-1

**Comment by DoubleDebug** [comment]
The cursor looks fine now when you simply put a password textbox on a form and try typing inside it.
But I tried setting the text property through code (e.g. materialTextBox1.Text = "Example") and it messed up the cursor again.

Don't know why this happens, seems like a very odd issue.

**Comment by orapps44** [comment]
I can reproduce the behaviour (only when Password property is set tot true) but I don't know how to fix that.

Soon I will release a variant of MaterialTextbox based on MaterialMultiLineTextBox2.
Approach is completely different, i hope this will solved that issue.

**Comment by ogi-sy** [comment]
![image](https://user-images.githubusercontent.com/72239346/127430228-4efbea61-96a4-49a7-aa04-54e52fc85f81.png)
In fact, the internal font of Richtextbox is inconsistent with the displayed font. The focus position uses the size of the internal font, so it has to be set to a single font
as follows
         protected override void OnCreateControl()
         {
             base.OnCreateControl();
             **LanguageOption = RichTextBoxLanguageOptions.DualFont;**
　　　.......

↓
![image](https://user-images.githubusercontent.com/72239346/127431120-a5810cfc-07b7-44c0-92ce-37fd386b57e0.png)

**Comment by orapps44** [comment]
@ogi-sy thank you for this solution.
Can you prepare a PR ?
I will review it and merge it.

**Comment by ogi-sy** [comment]
@orapps44  Thank you for the wonderful source code
How do I PR?
I looked at the demo code of MaterialTextBox, it uses "Roboto", 16 LogicalFont, and it does not display Chinese, Japanese, and Korean well. For testing, I replaced it with Japanese font in MaterialSkinManager.cs, such as: メイリオ (Meiryo). So I saw the problem of cursor misplaced.
I found the font change problem of RichTextBox, and finally in the OnCreateControl method of MaterialTextBox.cs I just added the following line of code to solve the problem

  **LanguageOption = RichTextBoxLanguageOptions.DualFont;**

Maybe inheriting TextBox is better than RichTextBox.

**Comment by orapps44** [comment]
@ogi-sy unfortunnately your proposal doesn't solve issue when password is set and text is set by code at startup.

**Comment by ogi-sy** [comment]
@orapps44 
Yes, I have also seen this problem when password is set. 
In any case, your code has no problems in the English environment.
What's more frustrating is that when using Chinese, Japanese and other input, 
there is a word transformation process, 
which does not work because of the use of ControlStyles.UserPaint
but in .Net 6 it is work!

■TextBox
![image](https://user-images.githubusercontent.com/72239346/127793299-19cb0ae3-11b2-46d3-b6aa-7c7af1d1d26b.png)

■the use of ControlStyles.UserPaint
![image](https://user-images.githubusercontent.com/72239346/127793437-3754f9bc-a2fc-4a9d-a559-f756d70345d2.png)

![image](https://user-images.githubusercontent.com/72239346/127793455-ee314c12-06ed-4f76-8079-115a67619790.png)

This is what I can think of now. 
Just like the picture below, 
add the native TextBox and Label to the control. 
When the TextBox gets the focus, 
the Label covers the TextBox, then displays it, moves upward, and the font gradually becomes smaller.
..........

![image](https://user-images.githubusercontent.com/72239346/127793903-40ef115c-320a-4cad-ba23-70441ebd8b03.png)

**Comment by ogi-sy** [comment]
@orapps44 
This is the example I implemented with Label and TextBox
[https://github.com/ogi-sy/ginbow/blob/main/MaterialTextBox2.cs](url)

**Comment by Li98k** [comment]
The MaterialTextBox cannot enter Chinese characters

When you enter Chinese in this control, the Chinese input box is closed

**Comment by Quekie** [comment]
> @orapps44 Thank you for the wonderful source code How do I PR? I looked at the demo code of MaterialTextBox, it uses "Roboto", 16 LogicalFont, and it does not display Chinese, Japanese, and Korean well. For testing, I replaced it with Japanese font in MaterialSkinManager.cs, such as: メイリオ (Meiryo). So I saw the problem of cursor misplaced. I found the font change problem of RichTextBox, and finally in the OnCreateControl method of MaterialTextBox.cs I just added the following line of code to solve the problem
> 
> **LanguageOption = RichTextBoxLanguageOptions.DualFont;**
> 
> Maybe inheriting TextBox is better than RichTextBox.
@orapps44
Hey I fond a input method [sougou](https://pinyin.sogou.com/) which can input chinese ， i don't know how it works

**Comment by orapps44** [comment]
Hey,

Use `MaterialTextBox2` control instead of `MaterialTextBox`.

As allready mentioned :

> Roboto supports Latin, Greek (partial) and Cyrillic scripts.
On Android, the Noto font is used for languages not supported by Roboto, including Chinese (simplified and traditional), Japanese, Korean, Thai and Hindi.

A good improvement would be to add support of Noto font.
