### ISSUE TITLE
Text box cursor bug

### ISSUE THREAD

**Issue by goto3** [leocb/MaterialSkin#19]
Hello, when you type symbols in a text box the cursor is misplaced:
![image](https://user-images.githubusercontent.com/16456164/66594258-28ce0b80-eb6f-11e9-9bce-982881b6003b.png)

Version: latest v2.0.0

**Comment by leocb** [comment]
Hmm I seen this on a PC that did not have Roboto installed.
here's a SS on my pc 
![image](https://user-images.githubusercontent.com/8310271/66595403-47cd9d00-eb71-11e9-939d-43d10f0a498a.png)
Do you have the font installed? if not, could you install it and check if the problem persists?

Currently the textbox uses a hacky way to display the cursors by sort of hiding the "real" textbox behind the one I draw, I don't like this current implementation too much because it causes these weird misalignment and I'm planning to change it.

If you or someone else wants to research a better way to implement complete custom textbox on windows forms, please do! Microsoft did not do a good job to support them ;/

**Comment by goto3** [comment]
yeah, that fixed the issue. Thank you.
Is there a way to install the font without user intervention?

**Comment by leocb** [comment]
If you package the app in a installer, then you can install the font too, otherwise I don't think it's possible (nor recommended)
But I'll keep an eye out for different implementations of a custom textbox, one option is to calculate the caret (cursor) position by getting the char width up to that point and then, by doing some math, positioning it correctly. This would be kinda of a nightmare and maybe slow for long strings. I'll keep investigating

**Comment by goto3** [comment]
Ok, I added the fonts to the resources in WinForms project, then set each one Build Action to Embedded Resource:
![image](https://user-images.githubusercontent.com/16456164/66598659-de04c180-eb77-11e9-8394-dd7fa61f2b2a.png)

this is working for now.

**Comment by goto3** [comment]
> ![image](https://user-images.githubusercontent.com/8310271/66595403-47cd9d00-eb71-11e9-

is there a way to change the Hint color on conditions?

**Comment by leocb** [comment]
Oh, I do that for the generated DLL, seems like you have to do it on the app as well.. interesting, will investigate further.
I'm working on changing hint colors now (error handling right? I need them too haha)
I plan on releasing a new version tomorrow... maybe... if all goes right :)

**Comment by goto3** [comment]
Nice. Thank you very much for this project. Very useful for the University project I am making.

**Comment by leocb** [comment]
Probably fixed on #24 further testing is still required
