### ISSUE TITLE
Focused button visibility

### ISSUE THREAD

**Issue by valimaties** [leocb/MaterialSkin#279]
Hi,
I'm wondering if someone thought of implementing a "focused color" property in `MaterialButton` control. Textboxes have that animated bottom line which tells you which control has focus, but button have not. 
@orapps44, could you implement a `FocusedForeColor` or `FocusedBackColor` property (or both) on `MaterialButton` to be able to show which button in form has the focus?

Thanks.

**Comment by orapps44** [comment]
Hi @valimaties ,

Custom colors will not be supported, this is due to the effort to keep the interface consistent across the whole app. 
Use the HighEmphasis and UseAccent property to grab the user attention when mouse over it.

If you're interested by showing focused control after Tab key press, then yes it is not supported. Adding this feature may be interesting but probably tricky. I won't work on it, but if anyone want to contribute feel free to propose a PR.
