### ISSUE TITLE
Black background on controls like slider, checkbox, combobox...

### ISSUE THREAD

**Issue by AnErrupTion** [leocb/MaterialSkin#30]
Hey,
I've recently discovered a bug when using MaterialSkin 2.0.0, basically when I use a control like slider, checkbox or combobox (and maybe more) then the background isn't transparent, but black. I've tried to set it to another color but still same thing. Don't know where the error could be, I've correctly installed it.

~ AnErrupTion

**Comment by leocb** [comment]
Hi, thanks for reporting! :)
Is this when using the material controls or the windows forms default controls? Are using the black theme? Did you set the color in the skinManager? Please refer to the example app on how to properly setup your environment and please check if the steps I commented on this issue solve your problem: #29 

If you continue to have problems, please describe every step you take until the problem occurs so I can replicate it

**Comment by AnErrupTion** [comment]
It's when using the material controls. For the black theme, I don't know what you mean (maybe the dark theme?) If it's the dark theme, then yes I'm using it, but it does the same thing with the light theme.
I've tried to compile the library with the comment you've posted, still same problem.
Also, the problem is only visible on the Form Design in Visual Studio. When I run the program, everything is fine. I'm attaching 2 screenshots so you can see.
![image](https://user-images.githubusercontent.com/49339966/69659023-a4cbd680-107d-11ea-9c44-b3d017da6831.png)

![image](https://user-images.githubusercontent.com/49339966/69659048-af866b80-107d-11ea-84dc-48b01de0d94e.png)

**Comment by leocb** [comment]
Ahh yes, this was a tricky one to catch the first time I saw it too. The dark theme has nothing to do with it.

FIX: The TabControl has the background Color set to `Transparent` by default, just change it to anything else, like white or dark-gray

Just a technical background if anyone wants to fix this before I do (at some point): This bug only happens in Design Time, and is caused by the logic Material Controls use on the paint event. they the parent back-color to create a pseudo-transparent backcolor for themselves, however, if the parent back-color is set to `transparent`, the GDI gets confused and just paints black. This doesn't happen at run-time because the MaterialSkinManager enforces the correct backcolor on all controls.

**Comment by AnErrupTion** [comment]
Thanks! I'll edit the material skin library to set the back color of material tab control to white, it fixed my issue!

**Comment by seikosantana** [comment]
I also found out that setting `UseVisualStyleBackColor` property of the containing `TabPage` to `false` also fixes the issue.
