### ISSUE TITLE
Some MaterialComponents Text have "+-1" Issue

### ISSUE THREAD

**Issue by byungmeo** [leocb/MaterialSkin#337]
![image](https://user-images.githubusercontent.com/37506142/153696142-289557ab-b56e-4eb8-bebc-9f9a7cd1689e.png)

![2022-02-12 12-46-08](https://user-images.githubusercontent.com/37506142/153695624-592d2f6e-fefd-4206-912f-628cef37d5be.gif)

HelloWorld! 
-> IfmmpXpsme"
-> GdkknVnqkc 

I don't know why actually occur this issue. 
and i haven't found a way to reproduce it in another way.

The same issue occurs with other components.
However, it is only that Issue has not occurred yet.

One thing is certain, this problem arises only for English and numbers.

++
I'm suspicious this is the default font problem of VisualStudio,
 and I wonder how default fonts are in the British and American regions.

I don't know if it's related. if Form Font changed to "Roboto"
Labels (Defalut component) Text to change -1 (only inside form editor)

![2022-02-12 12-58-30](https://user-images.githubusercontent.com/37506142/153695895-cec9afcb-39cc-4a33-b1e8-84811d7a2a49.gif)

**Comment by orapps44** [comment]
Hi,

I'm not realy sure what issue is due to ppor video quality.
If you try to change font and/or font size, this feature isn't supported at the moment (see #336 & #207).

**Comment by byungmeo** [comment]
@orapps44 
![image](https://user-images.githubusercontent.com/37506142/153707366-6f0886b1-ee6d-485b-9cf7-914834f0c175.png)

It's the same as this screenshot. (ex : Home -> Gnld)
I didn't change the font in this sample, and so did other settings.
That's why I thought the default font set in VisualStudio might be the problem.

**Comment by orapps44** [comment]
Do you mean you got this when running current master without changing anything ?

**Comment by orapps44** [comment]
Using your zip file and VS2019 or VS2022 everything ok on my side.

![image](https://user-images.githubusercontent.com/77468294/153715050-ec933909-13a3-46bb-a5b3-eb7f35ef43b5.png)

**Comment by byungmeo** [comment]
@orapps44 
I want to know the default font that works well. (not Roboto)
My VisualStudio's default font is "맑은 고딕".
This is basically set up when VisualStudio is installed in Korea.
I think this is a problem.

I am willing to change my default font to that font.
If you let me know, I'll try after changing the default font.

**Comment by valimaties** [comment]
Hi @byungmeo 
I think the problem is that you use an unsupported font by MaterialSkin. One more thing about Font property in all components, I think it must be hidden. DON'T change it, because MaterialSkin uses Roboto font family and this is render as it has to be in components. This is how is made MaterialSkin, for now. If this project does not helps you, this means you can not use MaterialSkin. Or you must make your own changes to MaterialSkin to be able to use NotoSans font family in your applications. I tried to make some changes to this project, but there are some problems by reading NotoSans font family, to add to MaterialSkin library font family, but right now it is not possible.

**Comment by byungmeo** [comment]
@valimaties 
thanks to answer.
Of course, I didn't change all the fonts of Material Component and left them as they were.

I think this is a regional problem for Visual Studio, but the symptoms were the same even if fonts in all possible areas were changed to English-based.

I'll try installing VisualStudio in English version.
If there is a positive result, I will mention it.

thank you!

**Comment by valimaties** [comment]
I've tried some days to find a possibility to add NotoSansKR font family, but I have some issue by reading font family:
`addFont` method adds fonts from resources to `privateFontCollection` collection. GDI+ method add it correctly only Roboto fonts family, but NotoSans is not read:

![TryingToAddFontFamily](https://user-images.githubusercontent.com/49796453/153817219-031ded60-5244-42dd-ae28-638c4568b2a1.png)

... so. we must dig in it...

**Comment by byungmeo** [comment]
@valimaties 
I'm sorry for not being able to help you directly.

I'm using this plug-in too well, so I'm going to endure and use this part to some extent.
and I will try many things to help contributors indirectly.

**Comment by byungmeo** [comment]
@valimaties @orapps44 
![image](https://user-images.githubusercontent.com/37506142/153988200-0c394394-1b36-4845-97f7-014ec5b5c56a.png)

I tried many things, such as reinstalling visual studio and changing the language pack to English.

As a result, this problem is not a difference between fonts and language packs, but a PC problem. Because, as a result of testing with the same environment on my other PC, there was no problem.

And this problem seems to be separate from the question of whether or not to support a specific font.

**Comment by byungmeo** [comment]
@valimaties @orapps44 
![image](https://user-images.githubusercontent.com/37506142/153991151-fd6e10a8-63d7-4d93-81e5-3fc0f3837bce.png)

I found a solution!

The problem was that the Roboto font was installed.

I don't know what this is related to, but after erasing the Roboto font, the font is output normally.

I'll close this issue! Thank you for your interest.

**Comment by JimCHH** [comment]
@byungmeo 
Hi, thank you for your findings. I know its a closed issue. 
However, I also have the same problem here.
The Text Rendering in some component will -1 (e.g. materialLabel, materialListBox).
`"BCDEF" -> "ABCDE"`

I have Roboto font installed on my Desktop, while running build 2.3.1, using VS2019 with zh-tw language setting.
I haven't tried to uninstall because it seems that other font is not supported for now. #207

I'll keep looking for solution to this.
