### ISSUE TITLE
MaterialComboBox does not refresh selected item when changed programmatically

### ISSUE THREAD

**Issue by jackhab** [leocb/MaterialSkin#341]
After selecting combo item programmatically via SelectedIndex property the combo does not refresh until mouse is moved over it.

This can be solved by calling Refresh() but I suppose there is more appropriate way to solve it in the control design (but I don't know how) so I'm posting it as an issue rather than pull request.

![1](https://user-images.githubusercontent.com/1982773/156343667-531a1d1a-b5de-423d-80f9-5709c0683901.gif)

![2](https://user-images.githubusercontent.com/1982773/156343736-062c2fa7-a6f9-4b06-994b-eaa4615a8c88.gif)

**Comment by valimaties** [comment]
Fixed in PR #342 
Added an improvement to ComboBox, which I personally used in my applications. When hit Del key or Backspace, the index of ComboBox will become -1.

![FixMaterialComboBoxSelectedIndexChangedRefresh](https://user-images.githubusercontent.com/49796453/156730052-19b50430-94f8-4c82-8de3-cdffe3cae2ce.gif)
