### ISSUE TITLE
Flashing when changing theme

### ISSUE THREAD

**Issue by ghost** [leocb/MaterialSkin#7]
Only the label background is slightly delayed changed, so its little uncomfortable.
It changed seamlessly in previous commits.

![gif](https://i.imgur.com/sdxmlFU.gif)

**Comment by leocb** [comment]
The old version did do this, but it was much faster because there were less controls on the form. This is inherit of how winforms cascade Paint events from parent to children. Maybe disabling the interface update while we run the for loop that changes the theme would help. I'll take a look at it, but feel free to open a PR

**Comment by leocb** [comment]
I'm marking this as won't fix because there's not much I can do about it, and it doesn't affect functionality so it's very low priority, if someone else want to try to fix it, please go ahead, but there are more important bugs to be squashed first
