### ISSUE TITLE
ALT + F4 will close the navigation bar alone

### ISSUE THREAD

**Issue by cxw3292008** [leocb/MaterialSkin#70]
Hi leocb,

Click the left navigation bar area, ALT + F4 will close the navigation bar alone, how can I avoid this problem? I hope the effect is that Alt + F4 can shut down the software, not a control.
![Uploading 20200315111255.png…]()

**Comment by leocb** [comment]
Hi, thanks for reporting. Yes, this is a "bug", it happens because I use 2 extra forms to show the drawer menu (what you're referring as navigation bar). You can subscribe to the "onClosing" event on the drawer and end the application there, this can be done on the "MaterialForm", that's where I create the menu.

**Comment by cxw3292008** [comment]
@leocb  ok,thx 😄
