### ISSUE TITLE
Drawer using panel

### ISSUE THREAD

**Issue by cairoutm** [leocb/MaterialSkin#79]
Hi;

First of all, thank you for this great UI. It's awesome.

This is actually a feature request and not a bug. I found out that we need to put tab control on the form in order to use drawer. It is possible that we use drawer with panel control as shown in [here](https://rjcodeadvance.com/disenar-interfaz-de-usuario-modernista-only-window-con-c-version-base/)? If we use tab control, then our main form will have too many controls. If we can load other form in panel, then we can distribute other controls in other form.

Thanks in advance

**Comment by leocb** [comment]
Hi, thanks for your suggestion.

At the moment, It's not possible to use any other control other than the tabControl. This is due to how deep I use the functionality of it to keep track of lots of things inside the drawer menu.

Looking at the example link you posted, as far as I can tell, you can copy and add any form you want on the the tabControl, if not, just add a panel on each tab before copying, and just do it once for all tabs when the Main Form loads instead of everytime you click on item in the menu. This is also known as pre-loading.

Also, the tabControl should keep the performance as it's design to not draw or update components that are not visible.

I'll leave this open so we can discuss any problems you find.

**Comment by leocb** [comment]
hi @cairoutm, I'd love to hear back from you, did my comment help you resolve your issue?
