### ISSUE TITLE
button color

### ISSUE THREAD

**Issue by dancoLgh** [leocb/MaterialSkin#98]
@leocb 
I would like to know if you can change the background color of a specific button

**Comment by leocb** [comment]
Hi, by design, the lib limits button colors to your defined primary and accent colors or black and white. See image bellow
![buttons](https://user-images.githubusercontent.com/8310271/66237911-a0fa8400-e6cc-11e9-8781-3e4c8cb0362b.png)
those can be changed by modifying the properties in the `Misc` category of the button
![image](https://user-images.githubusercontent.com/8310271/83562908-bab8c900-a4f0-11ea-9df9-8445918997e4.png)
